spring:
  application:
    name: poc-axon-saga-signature

  cloud:
    kubernetes:
      enabled: 'true'
      discovery.enabled: 'true'

  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://postgresql-db:5432/pdb?currentSchema=sig
    username: ${datasource_username}
    password: ${datasource_password}
    hikari:
      connectionTimeout: 30000
      idleTimeout: 600000
      maxLifetime: 7190000
      minimumIdle: 2
      maximumPoolSize: 50
    tomcat:
      max-idle: 2
      min-idle: 2

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: false
    hibernate:
      ddl-auto: validate

  kafka:
    bootstrap-servers: kafka-service:9092
    consumer:
      group-id: poc-axon-saga

eureka.client.enabled: 'false'

ribbon:
  eureka.enabled: 'false'
  NIWSServerListClassName: io.fabric8.kubeflix.ribbon.KubernetesServerList
  KubernetesNamespace: default
